# Library

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math 
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.model_selection import GridSearchCV
from sklearn import tree
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif
import time

# Import CSV

In [2]:
!wget 'https://drive.google.com/uc?export=download&id=12d0twzuV6oTh7BHhStlgrAib4c5VzjWa' -O salju_train.csv
!wget 'https://drive.google.com/uc?export=download&id=1TrLcjR_6pPsZ5XBLNYxOcryiWItV7WO9' -O salju_test.csv

--2021-05-28 11:46:53--  https://drive.google.com/uc?export=download&id=12d0twzuV6oTh7BHhStlgrAib4c5VzjWa
Resolving drive.google.com (drive.google.com)... 142.250.1.138, 142.250.1.102, 142.250.1.139, ...
Connecting to drive.google.com (drive.google.com)|142.250.1.138|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-0c-14-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ljco4od15pibu7s97qs1fqesb0ao166v/1622202375000/00150260977202157621/*/12d0twzuV6oTh7BHhStlgrAib4c5VzjWa?e=download [following]
--2021-05-28 11:46:54--  https://doc-0c-14-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ljco4od15pibu7s97qs1fqesb0ao166v/1622202375000/00150260977202157621/*/12d0twzuV6oTh7BHhStlgrAib4c5VzjWa?e=download
Resolving doc-0c-14-docs.googleusercontent.com (doc-0c-14-docs.googleusercontent.com)... 173.194.192.132, 2607:f8b0:4001:c0e::84
Connecting to doc-0c-14-docs.googleusercontent.com (doc-0c-14

In [3]:
df_train = pd.read_csv('salju_train.csv')
df_test = pd.read_csv('salju_test.csv')

# Exploratory Data

In [4]:
df_train

id     Tanggal KodeLokasi  ...  Suhu3pm  BersaljuHariIni  BersaljuBesok
0            1  01/06/2014         C4  ...     15.0               Ya          Tidak
1            2  15/07/2014        C10  ...     15.5               Ya             Ya
2            3  16/02/2011        C46  ...     29.6            Tidak          Tidak
3            4  08/08/2012        C36  ...     23.2            Tidak          Tidak
4            5  29/10/2016         C7  ...     18.1            Tidak          Tidak
...        ...         ...        ...  ...      ...              ...            ...
109090  109091  31/01/2009        C38  ...     22.1            Tidak             Ya
109091  109092  03/11/2010        C16  ...     24.4            Tidak             Ya
109092  109093  11/11/2010        C17  ...     19.8               Ya          Tidak
109093  109094  16/04/2012        C11  ...     29.2            Tidak          Tidak
109094  109095  09/10/2011        C16  ...     23.3               Ya          Tidak

[109095 rows x 24 columns]

In [5]:
df_test

Tanggal KodeLokasi  SuhuMin  ...  Suhu3pm  BersaljuHariIni  BersaljuBesok
0      04/11/2010        C39     11.0  ...     23.6               No             No
1      26/03/2015        C35     10.0  ...     18.9               No            Yes
2      22/03/2016        C18      9.2  ...     26.3               No             No
3      09/12/2011        C31     17.7  ...     26.4               No             No
4      20/05/2017        C14      2.3  ...      6.0              Yes             No
...           ...        ...      ...  ...      ...              ...            ...
18177  14/11/2012        C40      7.8  ...     24.0               No             No
18178  24/10/2015        C40     12.4  ...     25.7               No             No
18179  31/08/2010        C21      6.7  ...     22.0               No             No
18180  24/08/2013        C12     12.5  ...     25.4               No             No
18181  26/10/2011        C22     12.3  ...     15.4              Yes            Yes

[18182 rows x 23 columns]

# Preprocessing

In [6]:
df_train = df_train.replace(['Ya','Tidak'],[1,0])
df_test = df_test.replace(['Yes','No'],[1,0])

In [7]:
df_test

Tanggal KodeLokasi  SuhuMin  ...  Suhu3pm  BersaljuHariIni  BersaljuBesok
0      04/11/2010        C39     11.0  ...     23.6              0.0            0.0
1      26/03/2015        C35     10.0  ...     18.9              0.0            1.0
2      22/03/2016        C18      9.2  ...     26.3              0.0            0.0
3      09/12/2011        C31     17.7  ...     26.4              0.0            0.0
4      20/05/2017        C14      2.3  ...      6.0              1.0            0.0
...           ...        ...      ...  ...      ...              ...            ...
18177  14/11/2012        C40      7.8  ...     24.0              0.0            0.0
18178  24/10/2015        C40     12.4  ...     25.7              0.0            0.0
18179  31/08/2010        C21      6.7  ...     22.0              0.0            0.0
18180  24/08/2013        C12     12.5  ...     25.4              0.0            0.0
18181  26/10/2011        C22     12.3  ...     15.4              1.0            1.0

[18182 rows x 23 columns]

In [8]:
df_train = df_train.drop(['id','Tanggal','KodeLokasi','ArahAnginTerkencang','ArahAngin9am','ArahAngin3pm','BersaljuHariIni'], axis=1)
df_test = df_test.drop(['Tanggal','KodeLokasi','ArahAnginTerkencang','ArahAngin9am','ArahAngin3pm','BersaljuHariIni'], axis=1)

In [9]:
df_train.dropna(inplace=True)
df_test.dropna(inplace=True)

In [10]:
df_train

SuhuMin  SuhuMax  Hujan  ...  Suhu9am  Suhu3pm  BersaljuBesok
3           7.3     24.5    0.0  ...     15.3     23.2            0.0
4           5.9     20.3    0.0  ...     12.4     18.1            0.0
5          14.4     21.8    0.0  ...     16.7     21.1            0.0
6           7.7     18.7    0.2  ...     11.3     18.3            0.0
8          18.4     35.3    0.0  ...     23.7     34.9            0.0
...         ...      ...    ...  ...      ...      ...            ...
109080     16.8     34.1    0.0  ...     25.6     33.0            0.0
109082      8.7     19.0    0.0  ...     10.8     16.5            0.0
109088     14.3     26.2    0.0  ...     21.1     25.5            0.0
109090     20.1     23.7    0.0  ...     22.0     22.1            1.0
109093     10.8     29.8    0.0  ...     21.7     29.2            0.0

[43677 rows x 17 columns]

In [11]:
df_test

SuhuMin  SuhuMax  Hujan  ...  Suhu9am  Suhu3pm  BersaljuBesok
2          9.2     27.2    0.0  ...     13.9     26.3            0.0
3         17.7     27.0    0.0  ...     22.3     26.4            0.0
7         14.4     22.4    0.0  ...     18.3     20.9            0.0
8         20.3     33.7    0.0  ...     24.6     32.2            0.0
10         8.1     18.2    0.0  ...     10.3     17.7            0.0
...        ...      ...    ...  ...      ...      ...            ...
18170     13.4     24.9    0.0  ...     23.0     23.7            0.0
18174     14.6     27.8    0.0  ...     22.8     25.3            0.0
18177      7.8     25.8    0.0  ...     16.8     24.0            0.0
18178     12.4     26.6    0.0  ...     17.1     25.7            0.0
18180     12.5     26.7    0.0  ...     22.9     25.4            0.0

[7225 rows x 17 columns]

In [12]:
df_test.to_csv("data_salju_test.csv")

In [13]:
df_train.to_csv("data_salju_train.csv")

In [ ]:
# df_train = df_train.drop(['SuhuMin', 'KecepatanAngin9am', 'KecepatanAngin3pm', 'Suhu3pm'], axis=1)
# df_test = df_test.drop(['SuhuMin', 'KecepatanAngin9am', 'KecepatanAngin3pm', 'Suhu3pm'], axis=1)
# df_train = df_train.drop(['SuhuMin', 'SuhuMax', 'SinarMatahari', 'KecepatanAnginTerkencang', 'KecepatanAngin9am', 'Kelembaban9am', 'Kelembaban3pm', 'Suhu3pm'], axis=1)
# df_test = df_test.drop(['SuhuMin', 'SuhuMax', 'SinarMatahari', 'KecepatanAnginTerkencang', 'KecepatanAngin9am', 'Kelembaban9am', 'Kelembaban3pm', 'Suhu3pm'], axis=1)

In [ ]:
# imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
# imp_mean.fit(df_train)
# imp_mean.fit(df_test)
# df_train = imp_mean.transform(df_train)
# df_test = imp_mean.transform(df_test)

In [ ]:
X_train = df_train.iloc[:,:-1]
y_train = df_train.BersaljuBesok

X_test = df_test.iloc[:,:-1]
y_test = df_test.BersaljuBesok

In [ ]:
# sns.boxplot(data=X_train)
# plt.show()

In [ ]:
# sns.boxplot(data=X_test)
# plt.show()

In [ ]:
# for i in range(len(X_train.columns)-1):
#   q1 = X_train.iloc[:, i].quantile(0.25)
#   q3 = X_train.iloc[:, i].quantile(0.75)
#   iqr = q3 - q1

#   lb = q1 - (iqr * 1.5)
#   ub = q3 + (iqr * 1.5)
#   def apply(x):
#     if x > ub:
#       return ub
#     elif x < lb:
#       return lb
#     else:
#       return x

#   X_train.iloc[:, i] = X_train.iloc[:, i].apply(apply)

# for i in X_train.columns:
#   sns.boxplot(
#       data=X_train,
#       y=i
#   )
#   plt.show()

In [ ]:
X_test.shape

(7225, 16)

In [ ]:
y_test.shape

(7225,)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

X_test = scaler.fit_transform(X_test)

# New Section

In [ ]:
mi = mutual_info_classif(X_train, y_train.ravel(), discrete_features=False, random_state=42)
mi

array([0.00769771, 0.01283627, 0.05302671, 0.01203011, 0.10655135,
       0.03047153, 0.00119568, 0.0059187 , 0.04047509, 0.12580502,
       0.03699874, 0.03282637, 0.05938612, 0.0915871 , 0.006932  ,
       0.02297584])

In [ ]:
mi < 0.05

array([ True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True,  True, False, False,  True,  True])

In [ ]:
0.01 < mi

array([False,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True, False,  True])

# Modelling dan Evaluation

In [ ]:
# X_train_split, X_test_split, y_train_split, y_test_split = train_test_split(X_train, y_train, test_size=0.3, random_state=109)

SVM

In [ ]:
clf = SVC(kernel='rbf')
clf.fit(X_train, y_train)

clf.score(X_test, y_test)

0.8588235294117647

DC

In [ ]:
dc = DecisionTreeClassifier()
dc.fit(X_train, y_train)

dc.score(X_test, y_test)

0.791280276816609

In [ ]:
clf = tree.DecisionTreeClassifier()
score = cross_val_score(clf, X_test, y_test, cv=5)
score

array([0.783391  , 0.79238754, 0.79031142, 0.77024221, 0.78477509])

kNN

In [ ]:
model = KNeighborsClassifier(n_neighbors=3)

# Train the model using the training sets
model.fit(X_train,y_train)

#Predict Output
y_pred= model.predict(X_test) 
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.84


NB

In [ ]:
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.7983391003460207


RF

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

classifier = RandomForestClassifier(n_estimators=20, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[5329  260]
 [ 791  845]]
              precision    recall  f1-score   support

         0.0       0.87      0.95      0.91      5589
         1.0       0.76      0.52      0.62      1636

    accuracy                           0.85      7225
   macro avg       0.82      0.73      0.76      7225
weighted avg       0.85      0.85      0.84      7225

0.8545328719723183


In [ ]:
param_dict = {'C': [10, 100], 
              'gamma': [ 0.1, 0.01],
              'kernel': ['rbf']} 

grid = GridSearchCV(
    SVC(),
    param_grid=param_dict,
    cv=3,
    verbose=3,
    n_jobs=-1
)
grid.fit(X_train, y_train)

Fitting 3 folds for each of 4 candidates, totalling 12 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  12 out of  12 | elapsed: 19.0min finished


GridSearchCV(cv=3, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': [10, 100], 'gamma': [0.1, 0.01],
                         'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [ ]:
grid.best_estimator_

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
t0 = time.time()

clf = grid.best_estimator_

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(f'{metrics.classification_report(y_test, y_pred)}')
print(f'Time: {time.time()-t0}')

              precision    recall  f1-score   support

         0.0       0.88      0.95      0.91      5589
         1.0       0.77      0.54      0.63      1636

    accuracy                           0.86      7225
   macro avg       0.82      0.75      0.77      7225
weighted avg       0.85      0.86      0.85      7225

Time: 207.24202275276184


In [ ]:
# from sklearn.model_selection import GridSearchCV
  
# # defining parameter range
# param_dict = {'C': [1, 10, 100], 
#               'gamma': [ 0.1, 0.01],
#               'kernel': ['rbf','sigmoid','poly','linear']} 
  
# grid = GridSearchCV(SVC(), param_dict, refit = True, verbose = 3)
  
# # fitting the model for grid search
# grid.fit(X_train, y_train)

# Experiment

In [ ]:
df_train.isnull().sum()

SuhuMin                     0
SuhuMax                     0
Hujan                       0
Penguapan                   0
SinarMatahari               0
KecepatanAnginTerkencang    0
KecepatanAngin9am           0
KecepatanAngin3pm           0
Kelembaban9am               0
Kelembaban3pm               0
Tekanan9am                  0
Tekanan3pm                  0
Awan9am                     0
Awan3pm                     0
Suhu9am                     0
Suhu3pm                     0
BersaljuBesok               0
dtype: int64